---
title: "Distribuciones de probabilidad"
author: "Joshua Karim Rosales May"
format: html
editor: visual
---

## Definición

Una distribución probabilidad es una función que cumple los siguiente.

- $0\le F_X(X)\le 1$
- Si $x_1 < x_2$, entonces $F_x(x_1) \le F_x(X_2)$
- $P(a<X\le b) = F_X(b)-F_x(a)$

## Ejemplos

Las distribuciones de probabilidad pueden ser continuas y discretas, entre las distribuciones continuas tenemos a la distribución
Gaussiana, exponencial, uniforme, etc. Por ejemplo la distribución uniforme se define como:

$$
U(a,b) =
\begin{cases}
\frac{1}{b-a} & a <x<b\\
0 & \mbox{resto}
\end{cases}
$$
y se grafica como:

```{r uniforme}
#| echo: false
#| nessage: false
x <- seq(-1,3, length=2000)
u <- ifelse(x>0 & x<2, 0.5,0)
plot(x,u, type="l", main="Distribución uniforme", xlab="Tiempo", ylab="Valores", lwd=2, col="#ef476f")
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
